# Generated by Django 5.2.8 on 2025-12-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
